[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "intermodulation"
version = "0.1.0"
description = "Utilities for intermodulation experiments with MEG"
authors = ["Berk Gercek"]

[tool.poetry.dependencies]
python = "^3.10"
matplotlib = "*"
jupyter = "*"
tqdm = "*"
numpy = "*"
pandas = "*"
scikit-learn = "*"
scipy = "*"
psychopy = "2024.*"

[tool.black]
line-length = 99